
name: Compile GMpro Deauther Fixed Library

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Extract Project ZIP
        run: |
          # Mengekstrak file project kamu ke folder 'project_source'
          unzip -o GMpro87-AdminPortal-Modified.zip -d project_source
          # Memindahkan file agar file .ino utama berada di posisi yang benar untuk di-compile
          # Kita gunakan wildcard (*) agar script otomatis mencari file .ino di dalamnya
          cp -r project_source/* ./

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Library from Repo Zip
        run: |
          mkdir -p /home/runner/Arduino/libraries
          arduino-cli lib install "SimpleCLI"
          
          # Pastikan file ArduinoJson-5.13.5.zip juga ada di root repo kamu
          unzip -o ArduinoJson-5.13.5.zip -d /home/runner/Arduino/libraries/
          
          ls -R /home/runner/Arduino/libraries/

      - name: Compile GMpro Firmware
        run: |
          # Menggunakan FQBN yang kemarin berhasil
          # Script akan mencari file .ino utama yang tadi sudah diekstrak
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          ./*.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro87-Modified-Binary
          path: ./build/*.bin
